### ISSUE TITLE
DagsterIPCProtocolError: Timeout: read stream has not received any data in 15 seconds

### ISSUE THREAD

**Issue by pybokeh** [dagster-io/dagster#3738]
## Summary
When launching dagit, I get the following traceback:
```
d:\python38\envs\dagster_dev\lib\site-packages\dagster\cli\workspace\workspace.py:103: UserWarning: Error loading repository location brg_repositories.py:dagster.serdes.ipc.DagsterIPCProtocolError: Timeout: read stream has not received any data in 15 seconds

Stack Trace:
  File "d:\python38\envs\dagster_dev\lib\site-packages\dagster\cli\workspace\workspace.py", line 98, in _load_handle
    handle = self.create_handle_from_origin(origin)
  File "d:\python38\envs\dagster_dev\lib\site-packages\dagster\cli\workspace\workspace.py", line 83, in create_handle_from_origin
    return origin.create_handle()
  File "d:\python38\envs\dagster_dev\lib\site-packages\dagster\core\host_representation\origin.py", line 163, in create_handle
    return ManagedGrpcPythonEnvRepositoryLocationHandle(self)
  File "d:\python38\envs\dagster_dev\lib\site-packages\dagster\core\host_representation\handle.py", line 200, in __init__
    self.grpc_server_process = GrpcServerProcess(
  File "d:\python38\envs\dagster_dev\lib\site-packages\dagster\grpc\server.py", line 1040, in __init__
    self.server_process, self.port = open_server_process_on_dynamic_port(
  File "d:\python38\envs\dagster_dev\lib\site-packages\dagster\grpc\server.py", line 980, in open_server_process_on_dynamic_port
    server_process = open_server_process(
  File "d:\python38\envs\dagster_dev\lib\site-packages\dagster\grpc\server.py", line 957, in open_server_process
    wait_for_grpc_server(server_process, output_file)
  File "d:\python38\envs\dagster_dev\lib\site-packages\dagster\grpc\server.py", line 893, in wait_for_grpc_server
    event = read_unary_response(ipc_output_file, timeout=timeout, ipc_process=server_process)
  File "d:\python38\envs\dagster_dev\lib\site-packages\dagster\serdes\ipc.py", line 39, in read_unary_response
    messages = list(ipc_read_event_stream(output_file, timeout=timeout, ipc_process=ipc_process))
  File "d:\python38\envs\dagster_dev\lib\site-packages\dagster\serdes\ipc.py", line 152, in ipc_read_event_stream
    raise DagsterIPCProtocolError(

  warnings.warn(
Exception ignored in: <function RepositoryLocationHandle.__del__ at 0x000001B74F5829D0>
Traceback (most recent call last):
  File "d:\python38\envs\dagster_dev\lib\site-packages\dagster\core\host_representation\handle.py", line 47, in __del__
    self.cleanup()
  File "d:\python38\envs\dagster_dev\lib\site-packages\dagster\core\host_representation\handle.py", line 273, in cleanup
    if self.heartbeat_shutdown_event:
AttributeError: 'ManagedGrpcPythonEnvRepositoryLocationHandle' object has no attribute 'heartbeat_shutdown_event'
Loading repository...
Serving on http://127.0.0.1:3000 in process 8348
```

But the strange part is, I know what appears to fix, but it will only fix temporarily.  Basically, to fix, in my repository definition, I have to alternate between returning a list and returning the lazy, dict form.

So when the failure happens, if my repository definition returns a list, if I change to returning a dict, the problem goes away.   But let's say I shut down dagit after the end of the day and re-start dagit the following morning, I get the error again and the strange part is, if I change my return statement back to returning a list, re-start dagit, the error goes away.  I hope this makes sense to someone, it is very strange to me.  So basically, after each re-start of dagit, I have to switch between returning a list and returning a dict, which temporarily fixes the problem until I shutdown down dagit and re-start dagit, then the problem comes back.

My repository definition below:

```
@repository
def brg_repo():
    return [
        brg_pipeline
    ]
    # return {
    #     "pipelines": {
    #         "brg_pipeline": lambda: brg_pipeline
    #     }
    # }
```

I believe this problem started to happen with version 0.10.5 and I was hoping when upgrading to 0.10.6, it would go away, but problem still remains.

####
OS: Windows 10
dagster version: 0.10.5 - 0.10.6 with on-prem Postgres backend

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by gibsondan** [comment]
Hi @pybokeh - that is indeed very strange. Just to double-check: you're certain that it's specifically changing the code that causes it to work again (and not, say, restarting dagit twice)? For example, I assume you've tried restarting dagit multiple times, and it didn't ever work, but then changing the code back to a dict fixed it 100% of the time the next time you restarted? Just ruling it out since I'm struggling think of a reason that specific code change would make a difference, particularly non-deterministically like that.

One other question: Is that the full set of logs from dagit? If there's anything before that warning that looks suspicious, that would be a useful clue about why the server isn't starting up correctly.

**Comment by gibsondan** [comment]
Oh, one other thing that might be useful - even if dagit can't load your repository location when it starts up, you can still go to the "Status" page by clicking on Status in the left nav and try to reload the repository location (there should be a "Reload" link in the rightmost column under "Repository Locations"). So you should be able to test why the code won't load without needing to restart dagit - if it gives you any useful output in the console when you try to reload it that would also be useful to know.

**Comment by pybokeh** [comment]
@gibsondan That is all the output that shows up in the terminal running dagit.  I also have separate dagster-daemon instance and all my schedules have been running great with no issue.  I am running dagster locally and I have a suspicion that problem is caused by my company's VPN or some kind of network issue.  Next time it fails, I will try your suggestion of going to the "Status" page and see if I can get any debugging info from the console.  So far, I have not been able to duplicate with my personal laptop with normal home ISP network.

**Comment by pybokeh** [comment]
@gibsondan It is getting stranger.  I've upgraded to 0.10.9 and this time I am always getting an error, but this time, a different kind of error compared to when I was using 0.10.6 where the problem is intermittent.  But now with 0.10.9, I am always getting this error and nothing I can do.  I have not touched my codebase at all:

```
Traceback (most recent call last):
  File "D:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Python38\envs\webscrape_dev\lib\site-packages\dagster\grpc\__main__.py", line 4, in <module>
    grpc_command()
  File "D:\Python38\envs\webscrape_dev\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "D:\Python38\envs\webscrape_dev\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "D:\Python38\envs\webscrape_dev\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Python38\envs\webscrape_dev\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "D:\Python38\envs\webscrape_dev\lib\site-packages\dagster\cli\api.py", line 443, in grpc_command
    server = DagsterGrpcServer(
  File "D:\Python38\envs\webscrape_dev\lib\site-packages\dagster\grpc\server.py", line 770, in __init__
    check.invariant(
  File "D:\Python38\envs\webscrape_dev\lib\site-packages\dagster\check\__init__.py", line 162, in invariant
    raise_with_traceback(
  File "D:\Python38\envs\webscrape_dev\lib\site-packages\future\utils\__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
dagster.check.CheckError: Invariant failed. Description: max_workers must be greater than 1 if heartbeat is True
d:\python38\envs\dagster_dev\lib\site-packages\dagster\cli\workspace\workspace.py:103: UserWarning: Error loading repository location brg_repositories.py:dagster.serdes.ipc.DagsterIPCProtocolError: Process exited with return code 1 while waiting for events

Stack Trace:
  File "d:\python38\envs\dagster_dev\lib\site-packages\dagster\cli\workspace\workspace.py", line 98, in _load_handle
    handle = self.create_handle_from_origin(origin)
  File "d:\python38\envs\dagster_dev\lib\site-packages\dagster\cli\workspace\workspace.py", line 83, in create_handle_from_origin
    return origin.create_handle()
  File "d:\python38\envs\dagster_dev\lib\site-packages\dagster\core\host_representation\origin.py", line 164, in create_handle
    return ManagedGrpcPythonEnvRepositoryLocationHandle(self)
  File "d:\python38\envs\dagster_dev\lib\site-packages\dagster\core\host_representation\handle.py", line 270, in __init__
    self.grpc_server_process = GrpcServerProcess(
  File "d:\python38\envs\dagster_dev\lib\site-packages\dagster\grpc\server.py", line 1054, in __init__
    self.server_process, self.port = open_server_process_on_dynamic_port(
  File "d:\python38\envs\dagster_dev\lib\site-packages\dagster\grpc\server.py", line 1004, in open_server_process_on_dynamic_port
    server_process = open_server_process(
  File "d:\python38\envs\dagster_dev\lib\site-packages\dagster\grpc\server.py", line 981, in open_server_process
    wait_for_grpc_server(server_process, output_file)
  File "d:\python38\envs\dagster_dev\lib\site-packages\dagster\grpc\server.py", line 913, in wait_for_grpc_server
    event = read_unary_response(ipc_output_file, timeout=timeout, ipc_process=server_process)
  File "d:\python38\envs\dagster_dev\lib\site-packages\dagster\serdes\ipc.py", line 39, in read_unary_response
    messages = list(ipc_read_event_stream(output_file, timeout=timeout, ipc_process=ipc_process))
  File "d:\python38\envs\dagster_dev\lib\site-packages\dagster\serdes\ipc.py", line 147, in ipc_read_event_stream
    _poll_process(ipc_process)
  File "d:\python38\envs\dagster_dev\lib\site-packages\dagster\serdes\ipc.py", line 135, in _poll_process
    raise DagsterIPCProtocolError(

  warnings.warn(
Loading repository...
Serving on http://127.0.0.1:3000 in process 12208
```

I then downgraded to 0.10.6, then run dagit, no errors.  I then upgraded to 0.10.9, I am now again, constantly getting this error above.  I can be reached on Slack.  So in my workspace.yaml, I have defined 2 repositories (see bottom below).

What's weird is the other repository is running fine (sc_repositories.py), but this particular repository (brg_respositories.py) is where dagster is having problems.  This particular repository doesn't have schedule definitions, but the other one that is running fine, has schedule definitions.  So that is the only major difference I can think of between the 2.  I will define a schedule for brg_repositories.py and see if that makes a difference and report back.  But I wouldn't think repositories must have schedule definitions?


My "sc_repositories.py" below, I have schedules defined for it.  The "brg_repositories.py", I do not have schedules defined for it and this is the one that seems to be giving dagster problems.

```
load_from:
  - python_file:
      relative_path: sc_repositories.py
      executable_path: D:/Python38/envs/dagster_dev/Scripts/python.exe
  - python_file:
      relative_path: brg_repositories.py
      executable_path: D:/Python38/envs/webscrape_dev/Scripts/python.exe
```

**Comment by pybokeh** [comment]
Version 0.10.9:

![image](https://user-images.githubusercontent.com/3989299/110169668-058ca780-7dc7-11eb-96d8-0ae5579832e5.png)

Then clicking on "View error" link:
![image](https://user-images.githubusercontent.com/3989299/110169720-19380e00-7dc7-11eb-8239-0723ac76aa7c.png)

Chrome developer console output:
![image](https://user-images.githubusercontent.com/3989299/110169948-70d67980-7dc7-11eb-8b64-73efa9bc4b13.png)

**Comment by gibsondan** [comment]
Hi @pybokeh - I just messaged you on Slack with a possible theory about this.

**Comment by pybokeh** [comment]
@gibsondan Thanks Daniel!  Per our Slack convo, that was it.  My Python environment (my webscrape_dev) had an older version of dagster, dagit, etc.  After upgrading, now all is good!  Oh my gosh that was embarrassing haha.

**Comment by gibsondan** [comment]
No worries! We should have better error handling/detection when that happens.

**Comment by pybokeh** [comment]
@gibsondan FYI, I am still getting the original 15 seconds timeout error intermittently after issuing the dagit command.  I have been able to resolve by repeatedly issuing the dagit command until the error doesn't happen.  Recently, it only took 2 attempts.  I am on company VPN FWIW.

**Comment by gibsondan** [comment]
My best guess there is that your execution environment may be overloaded enough that it takes more than 15 seconds to spin up a new Python process - is that plausible? Does reloading the location in Dagit also resolve the issue?
