### ISSUE TITLE
AutoMaterializationPolicy Required Positional Arguments Error

### ISSUE THREAD

**Issue by MJRAJ01** [dagster-io/dagster#18966]
### Dagster version

1.5.3

### What's the issue?

I'm receiving the below error when creating an eager AutoMaterializationPolicy - is there documentation for adding these arguments or which version doesn't require these?

**Error**
`TypeError: AutoMaterializePolicy.__new__() missing 3 required positional arguments: 'on_missing', 'on_new_parent_data', and 'for_freshness'
`

**Code**
```
my_assets = load_assets_from_package_module(
    auto_materialize_policy=AutoMaterializePolicy.eager(),
)
```
**Context**

- Currently using Dagster version 1.5.3 and Python 3.10.12 both locally and in a Kubernetes deployment but have only seen the error in deployment when it reads the remote code location and fails to load it.
- The policy had been working in Dagster 1.4.2 but broke upon upgrading to 1.5.3. I haven't seen a previous version where these were arguments in the constructor, only as rules to add or remove

**Failed Resolutions**
1. Attempted adding the keyword arguments by hand (i.e. `AutoMaterializePolicy(on_missing=True)`) but this caused an unknown keyword error
2. Attempted creating a policy from scratch using the same methods as in the [documentation](https://docs.dagster.io/_modules/dagster/_core/definitions/auto_materialize_policy) seen below but it caused the same required positional arguments error

```
auto_materialize_policy=AutoMaterializePolicy(
        rules={
            AutoMaterializeRule.materialize_on_missing(),
            AutoMaterializeRule.materialize_on_parent_updated(),
            AutoMaterializeRule.materialize_on_required_for_freshness(),
            AutoMaterializeRule.skip_on_parent_outdated(),
            AutoMaterializeRule.skip_on_parent_missing(),
        },
    )
```

### Deployment type

Dagster Helm chart

### Additional information

Created initial discussion post here: https://github.com/dagster-io/dagster/discussions/18952

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.
