### PR TITLE
Fix regression when creating nested ConfigurableResource with pydantic >= v.2.5.0

### PR DESCRIPTION
**Pull request by benpankow**
## Summary

Slight tweak of @HynekBlaha's contribution in #28836 - this version adjusts our Pydantic union behavior for resources to account for a change in Pydantic 2.5.0 which uses 'smart unions' (https://github.com/pydantic/pydantic-core/pull/867). This smart union behavior attempted to initialize each member of the union using the input data, which called the constructor for `PartialResource` with invalid inputs.

This PR enforces left-to-right union evaluation, similar to what occurred pre-Pydantic 2.5.0.

## Test Plan

Unit test introduced in #28836.

## Changelog

Fixed an issue where using partial resources in Pydantic >= 2.5.0 could result in an unexpected keyword argument TypeError. (Thanks [@HynekBlaha](https://github.com/HynekBlaha)!)

### CODE REVIEW

**Comment by benpankow** [comment]
* **#28949** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/28949?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/28949?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `master`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: python_modules/dagster/dagster/_config/pythonic_config/resource.py [hunk 1]
```diff
@@ -834,7 +834,7 @@ def _is_annotated_as_resource_type(annotation: type, metadata: list[str]) -> boo
     """Determines if a field in a structured config class is annotated as a resource type or not."""
     from dagster._config.pythonic_config.type_check_utils import safe_is_subclass
 
-    if metadata and metadata[0] == "resource_dependency":
+    if metadata and any(m == "resource_dependency" for m in metadata):
```
Comment (benpankow) [inline python_modules/dagster/dagster/_config/pythonic_config/resource.py:837]: union mode `left_to_right` ends up in this metadata list, bumping resource dependency to second

**Comment by deepyaman** [comment]
Thanks @HynekBlaha @benpankow !
