### ISSUE TITLE
import error "from types import GenericAlias"

### ISSUE THREAD

**Issue by salilsaifuddin** [dagster-io/dagster#21920]
### Dagster version

latest

### What's the issue?

getting this exceptionOriginal exception was:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/dagster/_core/execution/watch_orphans.py", line 10, in <module>
    from types import GenericAlias
ImportError: cannot import name 'GenericAlias' from partially initialized module 'types' (most likely due to a circular import) (/usr/local/lib/python3.10/dist-packages/dagster/_core/execution/types.py)

Original exception was:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/dagster/_core/execution/watch_orphans.py", line 10, in <module>
    import signal
  File "/usr/lib/python3.10/signal.py", line 3, in <module>
    import signal
  File "/usr/lib/python3.10/signal.py", line 3, in <module>
    from enum import IntEnum as _IntEnum
  File "/usr/lib/python3.10/enum.py", line 2, in <module>
    from enum import IntEnum as _IntEnum
  File "/usr/lib/python3.10/enum.py", line 2, in <module>
    from types import MappingProxyType, DynamicClassAttribute
  File "/usr/local/lib/python3.10/dist-packages/dagster/_core/execution/types.py", line 1, in <module>
    from types import MappingProxyType, DynamicClassAttribute
    from typing import Dict
  File "/usr/local/lib/python3.10/dist-packages/dagster/_core/execution/types.py", line 1, in <module>
  File "/usr/lib/python3.10/typing.py", line 25, in <module>
    from typing import Dict
  File "/usr/lib/python3.10/typing.py", line 25, in <module>
    import contextlib
  File "/usr/lib/python3.10/contextlib.py", line 6, in <module>
    from functools import wraps
    import contextlib
  File "/usr/lib/python3.10/functools.py", line 22, in <module>
  File "/usr/lib/python3.10/contextlib.py", line 6, in <module>
    from functools import wraps
  File "/usr/lib/python3.10/functools.py", line 22, in <module>
    from types import GenericAlias
ImportError: cannot import name 'GenericAlias' from partially initialized module 'types' (most likely due to a circular import) (/usr/local/lib/python3.10/dist-packages/dagster/_core/execution/types.py)
    from types import GenericAlias

### What did you expect to happen?

getting error

### How to reproduce?

while do etl it happened

### Deployment type

Local

### Deployment details

local

### Additional information

nothing

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by TyShkan** [comment]
Having the same issue after update to 1.7.6 version (python 3.11)

**Comment by TyShkan** [comment]
Introduced [here](https://github.com/dagster-io/dagster/commits/master/python_modules/dagster/dagster/_core/execution/types.py) caused by the file name "types.py" shadowing stdlib module

FYI @mlarose

**Comment by gibsondan** [comment]
Hi, thanks for reporting this - we're working on a fix and it looks like this was indeed introduced in 1.7.6. Is it possible to confirm whether or not this error is preventing the run from completing?

**Comment by TyShkan** [comment]
@gibsondan jobs and schedules work as usual, runs complete correctly. It seems like it mostly affects execution of watch_orphans.py utility.

**Comment by gibsondan** [comment]
Got it - thanks for confirming.

Our current plan is to include a fix for this in the release planned for next week since the main impact appears to be logspew and the error doesn't fail runs or prevent logs from runs from being submitted (the utility process in question does some cleanup of orphaned subprocesses if the process running a step happens to crash mid-execution).

Downgrading to 1.7.5 should also prevent the error from being logged in the interim.
