### ISSUE TITLE
Issue upgrading Dagster to 1.7.15 using helm/celery/k8 worker

### ISSUE THREAD

**Issue by henrytseng** [dagster-io/dagster#23268]
### Dagster version

dagster, version 1.7.15

### What's the issue?

I'm seeing an error with after upgrading from `1.7.14` to `1.7.15`.  

```
 TypeError: create_k8s_job_task.<locals>._execute_step_k8s_job() got an unexpected keyword argument 'per_step_k8s_config'
 ```
 
Just a heads up, it looks like `per_step_k8s_config` was just added to `1.7.15` but it doesn't seem like it works with the earlier `1.7.14` image in DockerHub.  

### What did you expect to happen?

Minor version patch compatibility

### How to reproduce?

Run `celeryK8sRunLauncher` with Helm chart with 1.7.14 image deployed and kick off Celery based job.  

### Deployment type

Dagster Helm chart

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

**Comment by gibsondan** [comment]
Hi @henrytseng - just to confirm, the thing that you upgraded to 1.7.15 is the image running your code, while leaving the rest of the helm chart using the 1.7.14 release?

**Comment by alekseik1** [comment]
Hi, @henrytseng , I'm also experiencing same issue after upgrading to 1.7.15 in package and keeping docker image 1.7.14.
I think the image with updated dagster should be used. As of right now, there is no 1.7.15 tag on celery k8s in dockerhub (looks like it was not pushed when release happened).
@gibsondan could you please build & push a 1.7.15 tag [here](https://hub.docker.com/r/dagster/dagster-celery-k8s)?

**Comment by gibsondan** [comment]
Thanks for flagging that - we've identified the problem that occurred there and are pushing the images now.

**Comment by gibsondan** [comment]
The missing 1.7.15 image has now been pushed.
