### ISSUE TITLE
[dagster-dlt] extract_resource_metadata crashes with AttributeError when source yields no data

### ISSUE THREAD

**Issue by benmorrisalchera** [dagster-io/dagster#33572]
# `[dagster-dlt] extract_resource_metadata crashes with AttributeError when source yields no data`

## Summary

`DagsterDltResource.extract_resource_metadata` crashes when a dlt source returns no data, because `last_normalize_info` is accessed without a `None` guard.

## Bug

In `dagster_dlt/resource.py` ([line 134](https://github.com/dagster-io/dagster/blob/master/python_modules/libraries/dagster-dlt/dagster_dlt/resource.py#L134)):

```python
rows_loaded = dlt_pipeline.last_trace.last_normalize_info.row_counts.get(
    normalized_table_name
)
```

When a source yields no data, dlt skips the normalize step entirely. `dlt.pipeline.trace.last_normalize_info` returns `None` in this case (see [`dlt/pipeline/trace.py`](https://github.com/dlt-hub/dlt/blob/master/dlt/pipeline/trace.py) — `last_pipeline_step_trace("normalize")` finds no matching step). The chained `.row_counts` access then raises:

```
AttributeError: 'NoneType' object has no attribute 'row_counts'
```

This causes the entire asset materialization to fail even though `dlt_pipeline.run()` and `load_info.raise_on_failed_jobs()` both completed successfully — the crash happens during metadata extraction, not during the actual load.

## Reproduction

1. Create a `@dlt_assets` definition with a source that conditionally yields no data (e.g., an API that returns an empty response for a given time window).
2. Materialize the asset when the source has no data to return.
3. `extract_resource_metadata` raises `AttributeError`.

## Suggested fix

Guard `last_normalize_info` before accessing `.row_counts`:

```python
normalize_info = dlt_pipeline.last_trace.last_normalize_info
rows_loaded = (
    normalize_info.row_counts.get(normalized_table_name)
    if normalize_info is not None
    else None
)
if rows_loaded:
    base_metadata["rows_loaded"] = MetadataValue.int(rows_loaded)
```

## Context

- Introduced in PR #24306 (Sep 2024)
- Affects `dagster-dlt` 0.28.18 and current `master`
- The `.fetch_row_count()` chain on `DltEventIterator` has a similar gap — `fetch_row_count_metadata` raises when `jobs` metadata is an empty list (falsy), which also occurs on no-data runs.

**Comment by alex-fedorenk0** [comment]
One more edge case is when you have failure on load stage in dlt pipeline and next run in the same environment but new process. Then, even if dlt loads existing packages, dagster run will still fail because there is no normalize info in the current run.
