### PR TITLE
[Helm] Include flower configmap only when flower is enabled

### PR DESCRIPTION
**Pull request by LoHertel**
## Summary & Motivation

Even when Flower is disabled in the Helm `values.yaml`, the ConfigMap for Flower (`configmap-env-flower.yaml`) is still included in the Kubernetes deployment. This is unnecessary.

This PR adds a condition to exclude the Flower ConfigMap from the deployment, similar to how the ConfigMaps for the Daemon and Celery are handled.

## Changelog

> Include flower configmap only when flower deployment is enabled

### CODE REVIEW

**Comment by LoHertel** [comment]
Hi @alangenfeld, buildkite reported an error regarding Python 3.9. Asking you, because you have worked on dropping Python 3.9 support recently. Buildkite seems to still use a Python 3.9 image.
```
File "/root/.local/lib/python3.9/site-packages/buildkite_shared/step_builders/step_builder.py", line 1, in <module>
     from typing import TypeAlias, TypeGuard, Union
ImportError: cannot import name 'TypeAlias' from 'typing' (/usr/local/lib/python3.9/typing.py)
```

How can we resolve the failed buildkite run for this PR?

**Comment by alangenfeld** [comment]
thanks for the heads-up, switched to a 3.12 image and kicked off this rebuild https://buildkite.com/dagster/unit-tests/builds/2341

**Review by cmpadden — APPROVED** [review]
